# Generated by Django 3.2.12 on 2022-02-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=12, verbose_name='Numer konta')),
                ('balance', models.IntegerField(verbose_name='Stan konta')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=10, verbose_name='Numer karty')),
                ('expiration_date', models.DateField(verbose_name='Data ważności')),
                ('cvc_number', models.CharField(max_length=3, verbose_name='Numer CVC')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_receiver_firstname', models.CharField(max_length=50, verbose_name='Imię odbiorcy')),
                ('transfer_receiver_lastname', models.CharField(max_length=50, verbose_name='Nazwisko odbiorcy')),
                ('transfer_receiver_account_number', models.CharField(max_length=50, verbose_name='Nr konta odbiorcy')),
                ('transfer_amount', models.IntegerField(default=0.01, verbose_name='Kwota transakcji')),
                ('transfer', models.DateField(auto_now_add=True, verbose_name='Data przelewu')),
                ('balance_before_transfer', models.IntegerField(verbose_name='Stan przed transakcją')),
                ('balance_after_transfer', models.IntegerField(verbose_name='Stan po transakcji')),
                ('transaction_counter', models.IntegerField(default=0, verbose_name='Licznik transakcji')),
            ],
        ),
        migrations.CreateModel(
            name='AccountOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Imię')),
                ('lastnamename', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('addess', models.CharField(max_length=250, verbose_name='Adres')),
                ('city', models.CharField(max_length=250, verbose_name='Miasto')),
                ('country', models.CharField(max_length=250, verbose_name='Kraj')),
                ('date_of_birth', models.DateField(auto_now_add=True, verbose_name='Data urodzenia')),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccount.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='credit_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccount.creditcard'),
        ),
    ]
