# Generated by Django 3.2.12 on 2022-02-28 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default=False, max_length=250, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default=False, max_length=250, verbose_name='Miasto'),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default=False, max_length=250, verbose_name='Kraj'),
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data urodzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default=False, max_length=50, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(default=False, max_length=50, verbose_name='Imię'),
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(default=False, max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default=123123123, max_length=12, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=False, max_length=12, verbose_name='Numer konta'),
        ),
        migrations.DeleteModel(
            name='AccountOwner',
        ),
    ]
