# Generated by Django 3.2.12 on 2022-03-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0002_auto_20220228_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField(default=0.0, verbose_name='Kwota transakcji')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Data transakcji')),
                ('payments_counter', models.IntegerField(default=0, verbose_name='Licznik transakcji')),
            ],
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='transfer',
            new_name='transfer_date',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_title',
            field=models.CharField(default='Przelew środków', max_length=50, verbose_name='Tytuł przelewu'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=12, verbose_name='Numer konta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=250, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=250, verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Telefon'),
        ),
    ]
