# Generated by Django 3.2.12 on 2022-03-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0003_auto_20220301_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_receiver_account_number',
            field=models.CharField(max_length=5, verbose_name='Nr konta odbiorcy'),
        ),
    ]
