# Generated by Django 3.2.12 on 2022-03-01 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0004_alter_transfer_transfer_receiver_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='payment_amount',
            field=models.IntegerField(default=0.0, verbose_name='Kwota transakcji'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data transakcji'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='payments_counter',
            field=models.IntegerField(default=0, verbose_name='Licznik transakcji'),
        ),
    ]
