# Generated by Django 3.2.12 on 2022-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0005_auto_20220301_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=12, verbose_name='Hasło'),
        ),
    ]
